name = "workbench"
compatibility_date = "2026-03-05"

# Cloudflare Pages 构建配置
[build]
command = "npm install && npm run build"
publish = "dist"

# Pages Functions 配置
[functions]
directory = ""
node_compat = true